version: "3.8"

services:
  jetson:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        JETSON_UID: 1001
        JETSON_GID: 1001
    container_name: jetson-jenkins-container
    volumes:
      - ./:/workspace
    environment:
      - TZ=UTC
    ports:
      - "8080:8888" # Jenkins web interface
    devices:
      - "/dev/gpiomem:/dev/gpiomem" # For GPIO access
      - "/dev/i2c-1:/dev/i2c-1" # For I2C devices
    privileged: true # Required for full GPIO access
    restart: unless-stopped
    command: ["/usr/bin/java", "-jar", "/usr/share/jenkins/jenkins.war"]

networks:
  default:
    name: jetson-network
